"""
Comprehensive list of common first names for validation.
This list includes popular names from various cultures and time periods.
All names are stored in lowercase for case-insensitive matching.
"""

# Comprehensive list of common first names (case-insensitive matching)
# This list includes popular names from various cultures and time periods
COMMON_FIRST_NAMES = {
    # Common English names
    'alice', 'bob', 'charlie', 'david', 'emma', 'frank', 'grace', 'henry', 'isabella', 'jack',
    'kate', 'lily', 'mary', 'noah', 'olivia', 'paul', 'quinn', 'rachel', 'samuel', 'thomas',
    'una', 'victor', 'william', 'xavier', 'yasmine', 'zoe',
    # Additional common names
    'aaron', 'abigail', 'adam', 'adrian', 'aiden', 'alex', 'alexander', 'alexandra', 'alexis',
    'alice', 'alicia', 'allison', 'amanda', 'amelia', 'amy', 'andrew', 'angel', 'angela',
    'anna', 'annabelle', 'anne', 'anthony', 'aria', 'arianna', 'asher', 'ashley', 'aubrey',
    'audrey', 'ava', 'avery', 'bella', 'benjamin', 'brian', 'brooklyn', 'caleb', 'cameron',
    'carlos', 'caroline', 'carter', 'catherine', 'charlotte', 'chloe', 'christian', 'christopher',
    'claire', 'clara', 'colin', 'connor', 'daniel', 'danielle', 'diana', 'dylan', 'edward',
    'eleanor', 'elena', 'elijah', 'elizabeth', 'ella', 'ellie', 'emily', 'emma', 'eric',
    'ethan', 'evelyn', 'evie', 'finn', 'fiona', 'florence', 'gabriel', 'gabriella', 'george',
    'gianna', 'grace', 'grayson', 'hannah', 'harper', 'harry', 'hazel', 'henry', 'ian',
    'isaac', 'isabella', 'isabelle', 'jack', 'jackson', 'jacob', 'james', 'jane', 'jasmine',
    'jason', 'jayden', 'jennifer', 'jessica', 'john', 'jonathan', 'jordan', 'jose', 'joseph',
    'joshua', 'julia', 'julian', 'julie', 'justin', 'kate', 'katherine', 'kayla', 'kevin',
    'kimberly', 'kyle', 'laura', 'layla', 'leah', 'leo', 'liam', 'lily', 'lincoln', 'linda',
    'logan', 'lucas', 'lucy', 'luke', 'madison', 'marcus', 'margaret', 'maria', 'mark',
    'mason', 'matthew', 'maya', 'mia', 'michael', 'michelle', 'mila', 'molly', 'nancy',
    'natalie', 'nathan', 'nicholas', 'nicole', 'noah', 'nora', 'oliver', 'olivia', 'owen',
    'parker', 'patrick', 'paul', 'penelope', 'peter', 'philip', 'phoebe', 'quinn', 'rachel',
    'rebecca', 'riley', 'robert', 'ryan', 'samuel', 'sarah', 'savannah', 'scarlett', 'sean',
    'sophia', 'stephen', 'steven', 'susan', 'taylor', 'thomas', 'tyler', 'una', 'valentina',
    'victor', 'victoria', 'vincent', 'violet', 'william', 'wyatt', 'xavier', 'yasmine', 'zachary',
    'zoey', 'zoe',
    # Additional diverse names
    'aaliyah', 'abdul', 'ahmed', 'akira', 'amara', 'amir', 'anaya', 'andrea', 'angelina',
    'anika', 'anna', 'ariana', 'ariel', 'arjun', 'arthur', 'aryan', 'athena', 'austin',
    'autumn', 'axel', 'ayla', 'bella', 'blake', 'brayden', 'brody', 'brooke', 'caden',
    'callie', 'carson', 'casey', 'cassidy', 'celine', 'charlie', 'chase', 'clayton', 'cole',
    'colton', 'cooper', 'cora', 'cruz', 'dakota', 'damian', 'daniella', 'dante', 'daria',
    'davis', 'declan', 'delilah', 'derek', 'destiny', 'devon', 'diego', 'dixie', 'donna',
    'drew', 'eden', 'edgar', 'edison', 'eliana', 'elias', 'elise', 'eliza', 'elizabeth',
    'elliot', 'elsa', 'emery', 'emilia', 'emmanuel', 'enrique', 'enzo', 'erica', 'erin',
    'esther', 'eugene', 'evelyn', 'ezra', 'faith', 'felix', 'fernando', 'finley', 'finn',
    'fiona', 'fletcher', 'flora', 'frances', 'franklin', 'freya', 'gabriel', 'gabrielle',
    'gavin', 'gemma', 'geneva', 'george', 'georgia', 'gerald', 'gideon', 'gilbert', 'gina',
    'giovanni', 'giselle', 'gloria', 'gordon', 'grant', 'greyson', 'griffin', 'guadalupe',
    'gwen', 'hadley', 'hailey', 'haley', 'halle', 'hamza', 'hanna', 'harley', 'harmony',
    'harper', 'harrison', 'harvey', 'hayden', 'hayley', 'heather', 'hector', 'helena',
    'henry', 'hermione', 'holden', 'hope', 'hudson', 'hugo', 'hunter', 'ian', 'ibrahim',
    'ida', 'ignacio', 'ike', 'iliana', 'imani', 'imogen', 'india', 'indigo', 'ingrid',
    'ira', 'ireland', 'irene', 'iris', 'irving', 'isaac', 'isabel', 'isabella', 'isabelle',
    'isadora', 'isha', 'isla', 'israel', 'issac', 'itzel', 'iva', 'ivan', 'ivana', 'ivanna',
    'ivey', 'ivory', 'ivy', 'izaiah', 'izayah', 'izzy', 'jace', 'jack', 'jackson', 'jacob',
    'jade', 'jaden', 'jadiel', 'jaelyn', 'jaelynn', 'jagger', 'jaida', 'jaiden', 'jaime',
    'jairo', 'jake', 'jakob', 'jakobe', 'jalen', 'jamal', 'james', 'jameson', 'jamie',
    'jamir', 'jamison', 'janae', 'jane', 'janelle', 'janessa', 'janet', 'janice', 'janiyah',
    'jared', 'jase', 'jasiah', 'jason', 'jasper', 'javon', 'jax', 'jaxon', 'jaxson',
    'jaxton', 'jay', 'jayce', 'jayceon', 'jayda', 'jayden', 'jayla', 'jaylah', 'jaylee',
    'jaylen', 'jaylin', 'jaylynn', 'jayme', 'jayson', 'jazlyn', 'jazmin', 'jazmine',
    'jazmyn', 'jazmyne', 'jean', 'jefferson', 'jeffrey', 'jelani', 'jennifer', 'jenny',
    'jensen', 'jeremiah', 'jeremias', 'jeremy', 'jericho', 'jermaine', 'jerome', 'jerry',
    'jessica', 'jessie', 'jesus', 'jett', 'jewel', 'jillian', 'jimena', 'jimmy', 'joanna',
    'joaquin', 'jocelyn', 'joe', 'joel', 'joelle', 'joey', 'johan', 'johanna', 'john',
    'johnathan', 'johnathon', 'johnny', 'jolie', 'jon', 'jonah', 'jonas', 'jonathan',
    'jonathon', 'jones', 'jordan', 'jordy', 'jordyn', 'jorge', 'jose', 'josef', 'joseph',
    'josephine', 'josh', 'joshua', 'josiah', 'josie', 'josue', 'journee', 'journey', 'jovanni',
    'joy', 'joyce', 'juan', 'judah', 'jude', 'judith', 'judson', 'juelz', 'julia', 'julian',
    'juliana', 'julianna', 'julianne', 'julie', 'julien', 'juliet', 'juliette', 'julio',
    'julissa', 'julius', 'june', 'junior', 'juniper', 'justice', 'justin', 'justine',
    'justus', 'kade', 'kaden', 'kadence', 'kaeden', 'kaelyn', 'kaelynn', 'kai', 'kaia',
    'kaiden', 'kailani', 'kailey', 'kailyn', 'kaitlyn', 'kaitlynn', 'kaiya', 'kaleb',
    'kalel', 'kali', 'kaliyah', 'kallie', 'kamari', 'kamden', 'kamila', 'kamilah', 'kamryn',
    'kane', 'kara', 'kareem', 'karen', 'karina', 'karla', 'karlee', 'karlie', 'karson',
    'karter', 'kasey', 'kash', 'kason', 'kassidy', 'kate', 'katelyn', 'katelynn', 'katherine',
    'kathleen', 'kathryn', 'katie', 'katrina', 'kayden', 'kaydence', 'kayla', 'kaylee',
    'kayleigh', 'kaylie', 'kaylin', 'kaylyn', 'kaylynn', 'kayson', 'keagan', 'keaton',
    'keegan', 'keenan', 'kehlani', 'keira', 'keith', 'kellan', 'kellen', 'kelly', 'kelsey',
    'kelvin', 'kendall', 'kendra', 'kendrick', 'kenia', 'kennedy', 'kenneth', 'kenny',
    'kensley', 'kent', 'kenzie', 'kevin', 'keyla', 'khloe', 'kiana', 'kiara', 'kiera',
    'kieran', 'kiley', 'killian', 'kimber', 'kimberly', 'king', 'kingston', 'kinley',
    'kinsley', 'kira', 'kobe', 'kody', 'koen', 'kolby', 'kole', 'kolton', 'konnor',
    'kora', 'korbin', 'kourtney', 'kristen', 'kristian', 'kristin', 'kristina', 'kristopher',
    'krystal', 'kyla', 'kyle', 'kylee', 'kyleigh', 'kyler', 'kylie', 'kyra', 'lacey',
    'laila', 'lailah', 'lana', 'lance', 'landen', 'landon', 'landry', 'lane', 'laney',
    'lara', 'larry', 'laura', 'laurel', 'lauren', 'lauryn', 'lawrence', 'layla', 'laylah',
    'layne', 'layton', 'leah', 'leandro', 'leanna', 'leia', 'leif', 'leila', 'leilani',
    'leland', 'lena', 'lennon', 'lennox', 'leo', 'leon', 'leona', 'leonard', 'leonardo',
    'leonel', 'leonie', 'leonidas', 'leroy', 'leslie', 'lesly', 'levi', 'lewis', 'liam',
    'liana', 'libby', 'lila', 'lilah', 'lilian', 'liliana', 'lilianna', 'lilith', 'lillian',
    'lilliana', 'lillianna', 'lillie', 'lilly', 'lily', 'lina', 'lincoln', 'linda', 'lindsay',
    'lindsey', 'linnea', 'lisa', 'liv', 'liva', 'livia', 'livvy', 'lizbeth', 'lizeth',
    'lizzie', 'logan', 'lola', 'london', 'londyn', 'lonnie', 'lora', 'lorelai', 'lorelei',
    'loren', 'lorenzo', 'lori', 'louis', 'louise', 'luca', 'lucas', 'luciana', 'luciano',
    'lucille', 'lucy', 'luella', 'luis', 'luka', 'lukas', 'luke', 'lula', 'luna', 'lupe',
    'luther', 'lydia', 'lyla', 'lylah', 'lynn', 'lyra', 'lyric', 'mabel', 'maci', 'macie',
    'mack', 'mackenzie', 'macy', 'madden', 'maddison', 'maddox', 'madeline', 'madelyn',
    'madelynn', 'madeson', 'madilyn', 'madilynn', 'madison', 'madisyn', 'madyson', 'mae',
    'maeve', 'maia', 'maison', 'makai', 'makayla', 'makenna', 'makenzie', 'malachi', 'malakai',
    'malakhi', 'malaya', 'malcolm', 'maleah', 'malia', 'maliah', 'maliyah', 'mallory',
    'mamie', 'mandy', 'manuela', 'mara', 'marc', 'marcel', 'marceline', 'marcelo', 'marcus',
    'margaret', 'margot', 'mari', 'maria', 'mariah', 'mariam', 'mariana', 'marianna',
    'marie', 'mariela', 'mariella', 'marilyn', 'marina', 'mario', 'marisol', 'marissa',
    'maritza', 'mariyah', 'mark', 'markus', 'marlene', 'marlon', 'marquis', 'marshal',
    'marshall', 'martha', 'martin', 'martina', 'marvin', 'mary', 'maryam', 'mason', 'mateo',
    'mathew', 'mathias', 'matias', 'matilda', 'matteo', 'mattias', 'mattie', 'matthew',
    'maurice', 'mauricio', 'mavis', 'max', 'maxim', 'maximilian', 'maximiliano', 'maximo',
    'maximus', 'maxine', 'maxwell', 'maya', 'mayra', 'mckayla', 'mckenna', 'mckenzie',
    'mckinley', 'mclaughlin', 'meadow', 'meagan', 'meaghan', 'megan', 'meilani', 'melanie',
    'melany', 'melina', 'melinda', 'melissa', 'melody', 'melvin', 'memphis', 'mercedes',
    'meredith', 'merrick', 'mia', 'miah', 'micah', 'michael', 'michaela', 'micheal',
    'michelle', 'miguel', 'mikaela', 'mikayla', 'mike', 'mila', 'milan', 'milana', 'milani',
    'milena', 'miles', 'miley', 'millie', 'milo', 'milton', 'mina', 'mira', 'miracle',
    'miranda', 'miriam', 'misael', 'mitchell', 'mohamed', 'mohammad', 'mohammed', 'moises',
    'mollie', 'molly', 'monica', 'monroe', 'monserrat', 'montana', 'morgan', 'moriah',
    'moshe', 'muhammad', 'myla', 'myles', 'myra', 'nadia', 'nahlani', 'nahla', 'nancy',
    'naomi', 'natalia', 'natalie', 'nataly', 'natasha', 'nathalie', 'nathan', 'nathanael',
    'nathaniel', 'naya', 'nayeli', 'nehemiah', 'neil', 'nelly', 'nelson', 'neveah', 'nevaeh',
    'neville', 'nia', 'nicholas', 'nick', 'nickolas', 'nico', 'nicolas', 'nicole', 'niko',
    'nikolas', 'nikolai', 'nikolas', 'nina', 'noah', 'noe', 'noel', 'noelle', 'noemi',
    'nola', 'nolan', 'nora', 'norah', 'norma', 'nova', 'nyla', 'nylah', 'oakley', 'ocean',
    'octavia', 'odin', 'oliver', 'olivia', 'omar', 'omari', 'onyx', 'opal', 'ophelia',
    'orion', 'orlando', 'oscar', 'oswaldo', 'otis', 'ottilie', 'otto', 'owen', 'pablo',
    'paige', 'paisley', 'palmer', 'paola', 'paolo', 'parker', 'paris', 'parker', 'pascal',
    'patience', 'patricia', 'patrick', 'paula', 'paul', 'paulina', 'paulo', 'paxton',
    'payton', 'pearl', 'pedro', 'penelope', 'pepper', 'perla', 'perry', 'peter', 'peyton',
    'philip', 'phillip', 'phoebe', 'phoenix', 'piper', 'polo', 'porter', 'preston', 'prince',
    'princess', 'priscilla', 'priscilla', 'quinn', 'quinten', 'quinton', 'rachael', 'rachel',
    'raegan', 'raelyn', 'rafael', 'raiden', 'raina', 'ramon', 'ramona', 'randall', 'randy',
    'raphael', 'raquel', 'rashad', 'raul', 'raven', 'ravi', 'raymond', 'reagan', 'rebecca',
    'rebekah', 'reece', 'reed', 'reese', 'regan', 'reggie', 'regina', 'reginald', 'reid',
    'reign', 'reina', 'remi', 'remington', 'remy', 'rene', 'renee', 'reuben', 'reynaldo',
    'rhett', 'rhiannon', 'rhys', 'ria', 'ricardo', 'richard', 'ricky', 'riley', 'rina',
    'ripley', 'rita', 'river', 'rivka', 'roan', 'robert', 'roberto', 'robin', 'rocco',
    'rocky', 'rodney', 'rodrigo', 'roger', 'rohan', 'roland', 'roman', 'romano', 'romeo',
    'ronald', 'ronan', 'ronin', 'ronnie', 'rory', 'rosa', 'rosalie', 'rosalind', 'rosalinda',
    'rosalyn', 'rose', 'roselyn', 'rosemary', 'rosie', 'ross', 'rowan', 'rowen', 'roy',
    'royal', 'royce', 'ruben', 'ruby', 'rudy', 'rupert', 'russell', 'ruth', 'ruthie',
    'ryan', 'ryann', 'ryder', 'ryker', 'rylan', 'rylee', 'ryleigh', 'rylie', 'sabrina',
    'sadie', 'sage', 'saige', 'sailor', 'saint', 'salma', 'salvador', 'sam', 'samantha',
    'samara', 'samir', 'samson', 'samuel', 'sanaa', 'sandra', 'santana', 'santiago', 'santino',
    'santos', 'sara', 'sarah', 'sariah', 'sariyah', 'sasha', 'savanna', 'savannah', 'sawyer',
    'scarlett', 'scotty', 'sean', 'sebastian', 'selena', 'selina', 'serena', 'serenity',
    'sergio', 'seth', 'shane', 'shannon', 'sharon', 'shawn', 'shawna', 'shay', 'shea',
    'sheila', 'shelby', 'sheldon', 'sheridan', 'sherman', 'shiloh', 'shirley', 'shiv',
    'shivani', 'shmuel', 'shyann', 'siena', 'sienna', 'sierra', 'silas', 'simeon', 'simon',
    'simone', 'sincere', 'skye', 'skyla', 'skylar', 'skyler', 'sloane', 'sofia', 'sofia',
    'sofie', 'sol', 'sola', 'solomon', 'sonia', 'sonny', 'sophia', 'sophie', 'soren',
    'soraya', 'spencer', 'stella', 'stephanie', 'stephen', 'sterling', 'steve', 'steven',
    'stewart', 'stone', 'storm', 'stuart', 'sue', 'sullivan', 'summer', 'sunny', 'susan',
    'susanna', 'sutton', 'sydney', 'sylas', 'sylvia', 'sylvie', 'tadeo', 'tahlia', 'talia',
    'talon', 'tamara', 'tamia', 'tanner', 'tara', 'taraji', 'taryn', 'tatiana', 'tatum',
    'taylor', 'teagan', 'teddy', 'tegan', 'tenley', 'teresa', 'terrance', 'terrence', 'terry',
    'tessa', 'thaddeus', 'thai', 'thalia', 'thanos', 'thea', 'theo', 'theodore', 'theresa',
    'thomas', 'tiana', 'tianna', 'tiana', 'tierney', 'tiffany', 'tiger', 'tillie', 'timothy',
    'tina', 'titan', 'titus', 'tobias', 'toby', 'todd', 'tom', 'tomas', 'tommy', 'toni',
    'tony', 'tori', 'tory', 'trace', 'traci', 'tracy', 'travis', 'trent', 'trenton', 'trevor',
    'trey', 'trinity', 'tristan', 'tristen', 'tristin', 'triston', 'troy', 'truman', 'tucker',
    'turner', 'ty', 'tyler', 'tyree', 'tyrell', 'tyrese', 'tyrone', 'tyson', 'ulises',
    'ulysses', 'una', 'unique', 'uriah', 'uriel', 'ursula', 'valentina', 'valentino',
    'valeria', 'valerie', 'valery', 'van', 'vance', 'vanessa', 'vaughn', 'ved', 'vega',
    'velma', 'venus', 'vera', 'veronica', 'viana', 'vicente', 'victor', 'victoria', 'vida',
    'vienna', 'vihaan', 'vincent', 'vincenzo', 'violet', 'violeta', 'virginia', 'vivaan',
    'vivian', 'viviana', 'vivienne', 'vladimir', 'wade', 'walker', 'wallace', 'walter',
    'warren', 'watson', 'waylon', 'wayne', 'wesley', 'westin', 'weston', 'whitney', 'will',
    'willa', 'william', 'willie', 'willow', 'wilson', 'winston', 'winter', 'wisdom', 'wren',
    'wyatt', 'xander', 'xavier', 'ximena', 'xiomara', 'xyla', 'yadiel', 'yahir', 'yahya',
    'yara', 'yareli', 'yaretzi', 'yasmine', 'yazmin', 'yehuda', 'yehudah', 'yisroel',
    'yliana', 'yoel', 'yolanda', 'yosef', 'yousef', 'yusuf', 'yuvan', 'yvette', 'yvonne',
    'zachariah', 'zachary', 'zack', 'zackary', 'zackery', 'zaiden', 'zain', 'zainab',
    'zaire', 'zakai', 'zander', 'zane', 'zara', 'zaria', 'zariah', 'zariyah', 'zavier',
    'zayden', 'zayn', 'zayne', 'zechariah', 'zeke', 'zella', 'zendaya', 'zeno', 'zeppelin',
    'zephyr', 'zeus', 'zia', 'ziva', 'zoe', 'zoey', 'zoie', 'zola', 'zora', 'zoya',
    'zuri', 'zyaire', 'zyan', 'zyon',
    # Jewish names and nicknames
    'shlomo', 'yoni', 'avi', 'chaim', 'yitzchak', 'itzchak', 'yaakov', 'yakov', 'yankel',
    'dovid', 'dov', 'menachem', 'mendel', 'baruch', 'tzvi', 'aryeh', 'arye', 'binyamin',
    'benny', 'eliezer', 'eli', 'meir', 'mayer', 'nachum', 'pinchas', 'pini', 'reuven',
    'shimon', 'zev', 'zvi', 'avraham', 'avram', 'avrum', 'avrumi', 'yechiel', 'yechezkel',
    'ezekiel', 'yisrael', 'yisroel', 'yossi', 'yossel', 'yehoshua', 'yoshua', 'yitzhak',
    'itzhak', 'yitzchok', 'chayim', 'haim', 'hayim', 'shalom', 'sholom', 'solomon',
    'zalman', 'hirsch', 'hershel', 'hersh', 'berel', 'berish', 'ber', 'boruch', 'benzion',
    'ben', 'gavriel', 'gabriel', 'gabi', 'gavri', 'mordechai', 'mordy', 'motti', 'mottel',
    'moshe', 'moses', 'mosh', 'mendy', 'natan', 'nathan', 'nati', 'noach', 'nataniel',
    'nathaniel', 'nissim', 'nissan', 'peretz', 'pessach', 'pesach', 'pinny', 'refael',
    'rafael', 'raffi', 'rube', 'shlomi', 'shmuel', 'samuel', 'shmuli', 'shmulik', 'simon',
    'simcha', 'simi', 'tuvia', 'tuvya', 'wolf', 'velvel', 'yechi', 'chezkel', 'sruly',
    'yonatan', 'yonathan', 'jonathan', 'aviel', 'avishai', 'aviv', 'avner',
    # Jewish female names
    'chana', 'chanah', 'hannah', 'rivka', 'rivkah', 'rebecca', 'sara', 'sarah', 'leah',
    'rachel', 'esther', 'ester', 'devorah', 'devora', 'deborah', 'miriam', 'miri', 'mirel',
    'mirele', 'shoshana', 'shoshanna', 'susan', 'suzanne', 'tzipporah', 'tzippy', 'zipporah',
    'zippy', 'yocheved', 'batya', 'bracha', 'chaya', 'chava', 'gittel', 'golda', 'hadassah',
    'hinda', 'malka', 'malkie', 'naomi', 'nechama', 'shaindy', 'shaindel', 'shira', 'tova',
    'yaffa', 'yona', 'yudit', 'zissel'
}

